# Generated by Django 2.2.16 on 2020-09-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200921_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kellen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
